name: Build and deploy Angular app to Azure Web App - A2-Simulador

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build

      - name: Zip build output
        run: |
          cd dist/math-a3-app/browser
          zip -r ../../../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_856C33ED74844BE1AFD1A22D0687012F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63C380A9C87B4DAC8B5956C62C9A19C6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D62A7D5FFD9944509D6D9DAF15A70E6D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'A2-Simulador'
          slot-name: 'Production'
          package: .
